
services:
  organize_photos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: organize_photos_web
    ports:
      - "8080:8080"
    volumes:
      # Mapeie os diretórios do host para o container
      # Utilize caminhos absolutos ou variáveis de ambiente para máxima flexibilidade
      - ${SOURCE_DIR:-E:/Imagens}:/app/arquivos
      - ${OUTPUT_DIR:-E:/Imagens_Organizadas}:/app/organizados
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    networks:
      - organize_network

networks:
  organize_network:
    driver: bridge
